version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*, status.*, check_suite.*
    name: Making a test
    validate: []
    pass:
      - do: comment
        payload:
          body: I am running
