name: check

on: 
  check_run:
  check_suite: 
  status:

jobs:
  something:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: |
          echo "state ${{ github.event.state }}"
          echo "debugging ${{ toJson(github.event) }}"
