name: check

on: 
  workflow_run:

jobs:
  something:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: |
          echo "state ${{ github.event.state }}"
          echo "debugging ${{ toJson(github.event) }}"
