name: check

on: 
  status

jobs:
  something:
    name: passing
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: |
          echo "when did I run?"
          echo "debugging ${{ toJson(github.event) }}"
