name: failing

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  something:
    name: failing
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: |
          nocommand
